name: code_vault
description: "A phone hosted code vault"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  shelf: ^1.4.1
  shelf_static: ^1.1.2
  shelf_multipart: ^2.0.1
  network_info_plus: ^7.0.0
  mime: ^2.0.0
  sqflite: ^2.3.3+1
  path: ^1.9.0
  code_text_field: ^1.1.0
  image_picker: ^1.1.2
  path_provider: ^2.1.3
  video_player: ^2.8.6
  shared_preferences: ^2.2.3
  image: ^4.2.0
  flutter_local_notifications: ^19.5.0
  cupertino_icons: ^1.0.8

  flutter_highlight: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.4
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - web/index.html
    - web/styles.css
    - web/app.js
