name: code_vault
description: "A phone hosted code vault"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  shelf: ^1.4.1
  shelf_static: ^1.1.2
  network_info_plus: ^5.0.3
  mime: ^1.0.5
  sqflite: ^2.3.3+1
  path: ^1.9.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.4
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - web/index.html
    - web/styles.css
    - web/app.js
